sudo: false
language: scala

jdk:
  - openjdk8
  - openjdk11

before_cache:
 - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
 - find $HOME/.sbt -name '*.lock' -delete
 - rm -rf $HOME/.sbt/*/dependency/module/dynamic
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt test